# Generated by Django 6.0.4 on 2026-05-09 18:58

from django.db import migrations, models


def sync_existing_status(apps, schema_editor):
    Perfil = apps.get_model('account', 'Perfil')

    for perfil in Perfil.objects.select_related('user').all():
        if perfil.user.is_active:
            perfil.status = 'ATIVO'
        else:
            perfil.status = 'PENDENTE_EMAIL'
        perfil.save(update_fields=['status'])


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_perfil_telefone_alter_perfil_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='status',
            field=models.CharField(choices=[('PENDENTE_EMAIL', 'Pendente de Confirmacao de E-mail'), ('PENDENTE_APROVACAO', 'Pendente de Aprovacao'), ('ATIVO', 'Ativo')], default='PENDENTE_EMAIL', max_length=24),
        ),
        migrations.RunPython(sync_existing_status, migrations.RunPython.noop),
    ]
