# Generated by Django 6.0.4 on 2026-06-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_perfil_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='status',
            field=models.CharField(choices=[('PENDENTE_EMAIL', 'Pendente de Confirmacao de E-mail'), ('PENDENTE_APROVACAO', 'Pendente de Aprovacao'), ('ATIVO', 'Ativo'), ('REJEITADO', 'Cadastro Recusado')], default='PENDENTE_EMAIL', max_length=24),
        ),
    ]
