# Generated by Django 6.0.4 on 2026-06-16 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_perfil_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissaoSubAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escopo', models.CharField(choices=[('equipamento', 'Equipamento'), ('livro', 'Livro')], max_length=20)),
                ('subadmin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissoes', to='account.perfil')),
            ],
            options={
                'unique_together': {('subadmin', 'escopo')},
            },
        ),
    ]
