# Generated by Django 5.1.4 on 2026-06-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_permissaosubadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='status',
            field=models.CharField(
                choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')],
                default='pendente',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='perfil',
            name='token_aprovacao',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='permissaosubadmin',
            name='escopo',
            field=models.CharField(
                choices=[
                    ('equipamento', 'Equipamento'),
                    ('livro', 'Livro'),
                    ('agendamento', 'Agendamento'),
                    ('emprestimo', 'Empréstimo'),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='permissaosubadmin',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='setor',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
