# Generated by Django 6.0.4 on 2026-07-03 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_perfil_id_alter_permissaosubadmin_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='setor',
        ),
        migrations.AddField(
            model_name='perfil',
            name='setores_gerenciados',
            field=models.ManyToManyField(blank=True, related_name='subadmins', to='account.setor'),
        ),
    ]
