# Generated by Django 6.0.4 on 2026-07-03 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_perfil_setor_perfil_setores_gerenciados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='setores_gerenciados',
        ),
        migrations.CreateModel(
            name='JurisdicaoSubAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pode_gerenciar_itens', models.BooleanField(default=False, verbose_name='Gerenciar Itens')),
                ('pode_gerenciar_emprestimos', models.BooleanField(default=False, verbose_name='Gerenciar Empréstimos')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.setor')),
                ('subadmin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jurisdicoes', to='account.perfil')),
            ],
            options={
                'unique_together': {('subadmin', 'setor')},
            },
        ),
        migrations.DeleteModel(
            name='PermissaoSubAdmin',
        ),
    ]
