# Generated by Django 6.0.4 on 2026-07-03 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_remove_perfil_setores_gerenciados_jurisdicaosubadmin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='setores_gerenciados',
            field=models.ManyToManyField(blank=True, related_name='subadmins', through='account.JurisdicaoSubAdmin', to='account.setor'),
        ),
    ]
