"""
Django settings for agende_enginelab project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production

DEBUG = config('DEBUG', default=False, cast=bool)

_env_secret_key = config('SECRET_KEY', default='')
if _env_secret_key:
    SECRET_KEY = _env_secret_key
elif DEBUG:
    SECRET_KEY = 'dev-only-secret-key-change-me-in-env'
else:
    raise RuntimeError('SECRET_KEY não configurada no ambiente')

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())

# Configurações de E-mail lendo do .env
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
EMAIL_ADMIN_LAB = config('EMAIL_ADMIN_LAB', default=EMAIL_HOST_USER)

DEFAULT_FROM_EMAIL = f'EngineLab UFC <{EMAIL_HOST_USER}>'

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'widget_tweaks',
    'account',
    'appointment',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'agende_enginelab.urls'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'appointment:home'
LOGOUT_REDIRECT_URL = 'login'

ACCOUNT_MAX_FAILED_LOGINS_PER_MINUTE = config('ACCOUNT_MAX_FAILED_LOGINS_PER_MINUTE', default=5, cast=int)
ACCOUNT_LOCKOUT_THRESHOLD = config('ACCOUNT_LOCKOUT_THRESHOLD', default=10, cast=int)
ACCOUNT_LOCKOUT_SECONDS = config('ACCOUNT_LOCKOUT_SECONDS', default=15 * 60, cast=int)
ACCOUNT_CAPTCHA_AFTER_FAILS = config('ACCOUNT_CAPTCHA_AFTER_FAILS', default=3, cast=int)

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'agende_enginelab.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

_db_engine = config('DB_ENGINE', default='')
if not _db_engine:
    _db_engine = 'django.db.backends.sqlite3' if DEBUG else 'django.db.backends.postgresql'

if _db_engine == 'django.db.backends.sqlite3':
    _sqlite_name = config('DB_NAME', default='')
    DATABASES = {
        'default': {
            'ENGINE': _db_engine,
            'NAME': _sqlite_name or (BASE_DIR / 'db.sqlite3'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': _db_engine,
            'NAME': config('DB_NAME', default=''),
            'USER': config('DB_USER', default=''),
            'PASSWORD': config('DB_PASSWORD', default=''),
            'HOST': config('DB_HOST', default='localhost'),
            'PORT': config('DB_PORT', default='5432'),
        }
    }

    if not DEBUG:
        for _k in ('NAME', 'USER', 'PASSWORD'):
            if not DATABASES['default'][_k]:
                raise RuntimeError(f'DB_{_k} não configurado no ambiente')

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'agende_enginelab_default',
    }
}

SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=False, cast=bool)
SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', default=SECURE_SSL_REDIRECT, cast=bool)
CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', default=SECURE_SSL_REDIRECT, cast=bool)
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_REFERRER_POLICY = 'same-origin'

USE_X_FORWARDED_HOST = config('USE_X_FORWARDED_HOST', default=False, cast=bool)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https') if config('USE_SECURE_PROXY_SSL_HEADER', default=False, cast=bool) else None

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
