# Generated by Django 6.0.4 on 2026-06-16 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0004_alter_perfil_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('RECUSADO', 'Recusado'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=12)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='account.setor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data', '-hora_inicio'],
            },
        ),
    ]
