# Generated by Django 6.0.4 on 2026-07-03 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='motivo',
        ),
    ]
