# Generated by Django 6.0.4 on 2026-07-03 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_remove_agendamento_motivo'),
        ('catalog', '0008_emprestimo_vezes_renovado'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='dia_inteiro',
            field=models.BooleanField(default=False, verbose_name='Dia Inteiro'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='equipamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos', to='catalog.equipamento'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='livro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos', to='catalog.livro'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='hora_fim',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de Fim'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de Início'),
        ),
    ]
