# Generated by Django 6.0.4 on 2026-07-05 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_agendamento_dia_inteiro_agendamento_equipamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='data_final',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Devolução'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='data',
            field=models.DateField(verbose_name='Data de Início'),
        ),
    ]
