# Generated by Django 6.0.4 on 2026-07-02 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_emprestimo_token_acao_alter_categoria_descricao_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emprestimo',
            options={'ordering': ['-data_inicio', '-id']},
        ),
    ]
