# Generated by Django 6.0.4 on 2026-07-02 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_emprestimo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='token_renovacao',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
