# Generated by Django 6.0.4 on 2026-07-03 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_perfil_id_alter_permissaosubadmin_id_and_more'),
        ('catalog', '0004_emprestimo_token_renovacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipamentos', to='account.setor', verbose_name='Setor'),
        ),
        migrations.AddField(
            model_name='livro',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='livros', to='account.setor', verbose_name='Setor'),
        ),
    ]
