# Generated by Django 6.0.4 on 2026-07-03 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_perfil_id_alter_permissaosubadmin_id_and_more'),
        ('catalog', '0005_equipamento_setor_livro_setor'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='account.setor', verbose_name='Setor'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
        migrations.AlterUniqueTogether(
            name='categoria',
            unique_together={('nome', 'setor')},
        ),
    ]
