# Generated by Django 6.0.4 on 2026-07-03 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_perfil_setores_gerenciados'),
        ('catalog', '0006_categoria_setor_alter_categoria_nome_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipamento',
            options={'ordering': ['nome'], 'verbose_name': 'Item', 'verbose_name_plural': 'Itens'},
        ),
        migrations.AlterField(
            model_name='categoria',
            name='setor',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='account.setor', verbose_name='Setor'),
            preserve_default=False,
        ),
    ]
