# Generated by Django 6.0.4 on 2026-07-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_equipamento_options_alter_categoria_setor'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='vezes_renovado',
            field=models.PositiveIntegerField(default=0, verbose_name='Vezes Renovado'),
        ),
    ]
