# Generated by Django 6.0.4 on 2026-07-05 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_emprestimo_vezes_renovado'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='data_devolucao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Devolução Real'),
        ),
    ]
