# Generated by Django 6.0.4 on 2026-08-04 15:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_emprestimo_data_devolucao'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='data_solicitacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data da Solicitação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='dia_inteiro',
            field=models.BooleanField(default=True, verbose_name='Dia Inteiro'),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='hora_fim',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de Fim'),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de Início'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_inicio',
            field=models.DateField(verbose_name='Data de Início do Uso'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('ativo', 'Emprestado'), ('finalizado', 'Devolvido'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=20),
        ),
        migrations.DeleteModel(
            name='FilaEspera',
        ),
    ]
