# Generated by Django 6.0.4 on 2026-08-05 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_emprestimo_data_solicitacao_emprestimo_dia_inteiro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipamento',
            name='status',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='status',
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='item_nome_snapshot',
            field=models.CharField(blank=True, max_length=150, verbose_name='Item (registro histórico)'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='equipamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emprestimos', to='catalog.equipamento'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='livro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emprestimos', to='catalog.livro'),
        ),
    ]
